version: 2

jobs:
  convert:
    docker: [{image: "perl:5.24-threaded"}]
    steps:
    working_directory: /tmp/sqlserver2pgsql
    steps:
    - run:
        name: Install debian packages
        command: >
          apt update -y &&
          apt install -y --no-install-recommends bats git openssh-client
    - checkout
    - run:
        name: Executing tests
        environment:
          # Inject APT packaged dependencies.
          PERL5LIB: /usr/lib/x86_64-linux-gnu/perl5/5.24:/usr/share/perl5
        command: prove --verbose
    - store-artifacts:
        path: /tmp/artifacts

workflows:
  version: 2
  pipeline:
    jobs:
    - convert
    #- test
